apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yardpass-bot.resource-name" . }}
  labels:
    {{ include "yardpass-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "yardpass-bot.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "yardpass-bot.selector" . | nindent 8 }}
        version: {{ .Values.version | default "v1" }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./bot", "-c", "config.yaml"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: yardpass-bot
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: yardpass-bot
                  key: redis-url
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yardpass-bot
                  key: telegram-token
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 8081
