replicaCount: 1
version: v1

image:
  repository: ghcr.io/germanal2k4/yardpass-backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}

appLabel: yardpass-bot

secrets:
  databaseUrl: "postgres://yardpass:password@host.minikube.internal:5432/yardpass?sslmode=disable"
  redisUrl: "redis://host.minikube.internal:6379/0"
  telegramToken: ""

env:
  JWT_SECRET: ""
  API_BASE_URL: "http://yardpass-backend:8080"
  SERVICE_TOKEN: your-service-token
  LOG_LEVEL: info
  LOG_FORMAT: json
  LOG_TRANSPORT: elastic
  TRACER_ENABLED: "true"
  TRACER_URL: "jaeger-collector.istio-system:4317"
  ELASTIC_URL: "http://elasticsearch:9200"

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false
