// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: apartments.sql

package db

import (
	"context"
)

const getApartmentByID = `-- name: GetApartmentByID :one
SELECT id, building_id, number, floor, created_at, updated_at
FROM apartments
WHERE id = $1
`

func (q *Queries) GetApartmentByID(ctx context.Context, id int64) (Apartment, error) {
	row := q.db.QueryRow(ctx, getApartmentByID, id)
	var i Apartment
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Number,
		&i.Floor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApartmentByResidentTelegramID = `-- name: GetApartmentByResidentTelegramID :one
SELECT a.id, a.building_id, a.number, a.floor, a.created_at, a.updated_at
FROM apartments a
INNER JOIN residents r ON a.id = r.apartment_id
WHERE r.telegram_id = $1
`

func (q *Queries) GetApartmentByResidentTelegramID(ctx context.Context, telegramID int64) (Apartment, error) {
	row := q.db.QueryRow(ctx, getApartmentByResidentTelegramID, telegramID)
	var i Apartment
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Number,
		&i.Floor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApartmentsByBuildingID = `-- name: GetApartmentsByBuildingID :many
SELECT id, building_id, number, floor, created_at, updated_at
FROM apartments
WHERE building_id = $1
ORDER BY number
`

func (q *Queries) GetApartmentsByBuildingID(ctx context.Context, buildingID int64) ([]Apartment, error) {
	rows, err := q.db.Query(ctx, getApartmentsByBuildingID, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Apartment
	for rows.Next() {
		var i Apartment
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Number,
			&i.Floor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
