// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buildings.sql

package db

import (
	"context"
)

const createBuilding = `-- name: CreateBuilding :one
INSERT INTO buildings (name, address)
VALUES ($1, $2)
RETURNING id, name, address, created_at, updated_at
`

type CreateBuildingParams struct {
	Name    string
	Address *string
}

func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, createBuilding, arg.Name, arg.Address)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildingByID = `-- name: GetBuildingByID :one
SELECT id, name, address, created_at, updated_at
FROM buildings
WHERE id = $1
`

func (q *Queries) GetBuildingByID(ctx context.Context, id int64) (Building, error) {
	row := q.db.QueryRow(ctx, getBuildingByID, id)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBuildings = `-- name: ListBuildings :many
SELECT id, name, address, created_at, updated_at
FROM buildings
ORDER BY name
`

func (q *Queries) ListBuildings(ctx context.Context) ([]Building, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Building
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
