// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Apartment struct {
	ID         int64
	BuildingID int64
	Number     string
	Floor      *int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Building struct {
	ID             int64
	Name           string
	Address        *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ApartmentCount int32
}

type Pass struct {
	ID          uuid.UUID
	ApartmentID int64
	// Car plate number (NULL for pedestrian guests)
	CarPlate  *string
	GuestName *string
	ValidFrom time.Time
	ValidTo   time.Time
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	// Resident who created this pass (NULL for legacy passes)
	ResidentID *int64
}

type Resident struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CarPlate    *string
	// IANA timezone for bot/UI display; optional, from user-shared location
	Timezone *string
}

type Rule struct {
	ID                         int64
	BuildingID                 int64
	QuietHoursStart            *string
	QuietHoursEnd              *string
	DailyPassLimitPerApartment int32
	MaxPassDurationHours       int32
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type ScanEvent struct {
	ID          int64
	PassID      uuid.UUID
	GuardUserID int64
	ScannedAt   time.Time
	Result      string
	Reason      *string
	Meta        []byte
}

// Test accounts: superadmin/admin123, admin/admin123, guard/guard123
type User struct {
	ID           int64
	Username     string
	Email        *string
	PasswordHash string
	Role         string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	// Building ID for guards/admins. NULL for superuser, required for guard/admin
	BuildingID      *int64
	ApartmentNumber *int32
}
