// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveTodayByApartmentID = `-- name: CountActiveTodayByApartmentID :one
SELECT COUNT(*)
FROM passes
WHERE apartment_id = $1
  AND status = 'active'
  AND created_at >= $2
`

type CountActiveTodayByApartmentIDParams struct {
	ApartmentID int64
	CreatedAt   time.Time
}

func (q *Queries) CountActiveTodayByApartmentID(ctx context.Context, arg CountActiveTodayByApartmentIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTodayByApartmentID, arg.ApartmentID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTodayByResidentID = `-- name: CountActiveTodayByResidentID :one
SELECT COUNT(*)
FROM passes
WHERE resident_id = $1
  AND status = 'active'
  AND created_at >= $2
`

type CountActiveTodayByResidentIDParams struct {
	ResidentID *int64
	CreatedAt  time.Time
}

func (q *Queries) CountActiveTodayByResidentID(ctx context.Context, arg CountActiveTodayByResidentIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTodayByResidentID, arg.ResidentID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPass = `-- name: CreatePass :one
INSERT INTO passes (id, apartment_id, resident_id, car_plate, guest_name, valid_from, valid_to, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING created_at, updated_at
`

type CreatePassParams struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
}

type CreatePassRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePass(ctx context.Context, arg CreatePassParams) (CreatePassRow, error) {
	row := q.db.QueryRow(ctx, createPass,
		arg.ID,
		arg.ApartmentID,
		arg.ResidentID,
		arg.CarPlate,
		arg.GuestName,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Status,
	)
	var i CreatePassRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getActivePassByCarPlate = `-- name: GetActivePassByCarPlate :one
SELECT p.id, p.apartment_id, p.resident_id, p.car_plate, p.guest_name, p.valid_from, p.valid_to, p.status, p.created_at, p.updated_at
FROM passes p
INNER JOIN apartments a ON p.apartment_id = a.id
WHERE p.car_plate = $1
  AND p.status = 'active'
  AND p.valid_from <= $2
  AND p.valid_to >= $2
  AND ($3::bigint IS NULL OR a.building_id = $3)
ORDER BY p.created_at DESC
LIMIT 1
`

type GetActivePassByCarPlateParams struct {
	CarPlate         *string
	ValidFrom        time.Time
	FilterBuildingID *int64
}

type GetActivePassByCarPlateRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetActivePassByCarPlate(ctx context.Context, arg GetActivePassByCarPlateParams) (GetActivePassByCarPlateRow, error) {
	row := q.db.QueryRow(ctx, getActivePassByCarPlate, arg.CarPlate, arg.ValidFrom, arg.FilterBuildingID)
	var i GetActivePassByCarPlateRow
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.ResidentID,
		&i.CarPlate,
		&i.GuestName,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePassesByApartmentID = `-- name: GetActivePassesByApartmentID :many
SELECT id, apartment_id, resident_id, car_plate, guest_name, valid_from, valid_to, status, created_at, updated_at
FROM passes
WHERE apartment_id = $1
  AND status = 'active'
  AND valid_from <= $2
  AND valid_to >= $2
ORDER BY created_at DESC
`

type GetActivePassesByApartmentIDParams struct {
	ApartmentID int64
	ValidFrom   time.Time
}

type GetActivePassesByApartmentIDRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetActivePassesByApartmentID(ctx context.Context, arg GetActivePassesByApartmentIDParams) ([]GetActivePassesByApartmentIDRow, error) {
	rows, err := q.db.Query(ctx, getActivePassesByApartmentID, arg.ApartmentID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePassesByApartmentIDRow
	for rows.Next() {
		var i GetActivePassesByApartmentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.ResidentID,
			&i.CarPlate,
			&i.GuestName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePassesByBuildingID = `-- name: GetActivePassesByBuildingID :many
SELECT p.id, p.apartment_id, p.resident_id, p.car_plate, p.guest_name, p.valid_from, p.valid_to, p.status, p.created_at, p.updated_at
FROM passes p
INNER JOIN apartments a ON p.apartment_id = a.id
WHERE a.building_id = $1
  AND p.status = 'active'
  AND p.valid_from <= $2
  AND p.valid_to >= $2
ORDER BY p.created_at DESC
`

type GetActivePassesByBuildingIDParams struct {
	BuildingID int64
	ValidFrom  time.Time
}

type GetActivePassesByBuildingIDRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetActivePassesByBuildingID(ctx context.Context, arg GetActivePassesByBuildingIDParams) ([]GetActivePassesByBuildingIDRow, error) {
	rows, err := q.db.Query(ctx, getActivePassesByBuildingID, arg.BuildingID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePassesByBuildingIDRow
	for rows.Next() {
		var i GetActivePassesByBuildingIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.ResidentID,
			&i.CarPlate,
			&i.GuestName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePassesByResidentID = `-- name: GetActivePassesByResidentID :many
SELECT id, apartment_id, resident_id, car_plate, guest_name, valid_from, valid_to, status, created_at, updated_at
FROM passes
WHERE resident_id = $1
  AND status = 'active'
  AND valid_from <= $2
  AND valid_to >= $2
ORDER BY created_at DESC
`

type GetActivePassesByResidentIDParams struct {
	ResidentID *int64
	ValidFrom  time.Time
}

type GetActivePassesByResidentIDRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetActivePassesByResidentID(ctx context.Context, arg GetActivePassesByResidentIDParams) ([]GetActivePassesByResidentIDRow, error) {
	rows, err := q.db.Query(ctx, getActivePassesByResidentID, arg.ResidentID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePassesByResidentIDRow
	for rows.Next() {
		var i GetActivePassesByResidentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.ResidentID,
			&i.CarPlate,
			&i.GuestName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPassByID = `-- name: GetPassByID :one
SELECT id, apartment_id, resident_id, car_plate, guest_name, valid_from, valid_to, status, created_at, updated_at
FROM passes
WHERE id = $1
`

type GetPassByIDRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetPassByID(ctx context.Context, id uuid.UUID) (GetPassByIDRow, error) {
	row := q.db.QueryRow(ctx, getPassByID, id)
	var i GetPassByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.ResidentID,
		&i.CarPlate,
		&i.GuestName,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPassesByApartmentIDAndStatus = `-- name: GetPassesByApartmentIDAndStatus :many
SELECT id, apartment_id, resident_id, car_plate, guest_name, valid_from, valid_to, status, created_at, updated_at
FROM passes
WHERE apartment_id = $1 AND status = $2
ORDER BY created_at DESC
`

type GetPassesByApartmentIDAndStatusParams struct {
	ApartmentID int64
	Status      string
}

type GetPassesByApartmentIDAndStatusRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetPassesByApartmentIDAndStatus(ctx context.Context, arg GetPassesByApartmentIDAndStatusParams) ([]GetPassesByApartmentIDAndStatusRow, error) {
	rows, err := q.db.Query(ctx, getPassesByApartmentIDAndStatus, arg.ApartmentID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPassesByApartmentIDAndStatusRow
	for rows.Next() {
		var i GetPassesByApartmentIDAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.ResidentID,
			&i.CarPlate,
			&i.GuestName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePass = `-- name: RevokePass :exec
UPDATE passes
SET status = 'revoked'
WHERE id = $1
`

func (q *Queries) RevokePass(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokePass, id)
	return err
}

const searchPassesByCarPlate = `-- name: SearchPassesByCarPlate :many
SELECT p.id, p.apartment_id, p.resident_id, p.car_plate, p.guest_name, p.valid_from, p.valid_to, p.status, p.created_at, p.updated_at
FROM passes p
INNER JOIN apartments a ON p.apartment_id = a.id
WHERE UPPER(REPLACE(p.car_plate, ' ', '')) LIKE $1::varchar
  AND ($2::bigint IS NULL OR a.building_id = $2)
ORDER BY p.created_at DESC
LIMIT $3::int
`

type SearchPassesByCarPlateParams struct {
	CarPlatePattern  string
	FilterBuildingID *int64
	MaxResults       int32
}

type SearchPassesByCarPlateRow struct {
	ID          uuid.UUID
	ApartmentID int64
	ResidentID  *int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) SearchPassesByCarPlate(ctx context.Context, arg SearchPassesByCarPlateParams) ([]SearchPassesByCarPlateRow, error) {
	rows, err := q.db.Query(ctx, searchPassesByCarPlate, arg.CarPlatePattern, arg.FilterBuildingID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPassesByCarPlateRow
	for rows.Next() {
		var i SearchPassesByCarPlateRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.ResidentID,
			&i.CarPlate,
			&i.GuestName,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePass = `-- name: UpdatePass :one
UPDATE passes
SET apartment_id = $2, car_plate = $3, guest_name = $4, valid_from = $5, valid_to = $6, status = $7
WHERE id = $1
RETURNING updated_at
`

type UpdatePassParams struct {
	ID          uuid.UUID
	ApartmentID int64
	CarPlate    *string
	GuestName   *string
	ValidFrom   time.Time
	ValidTo     time.Time
	Status      string
}

func (q *Queries) UpdatePass(ctx context.Context, arg UpdatePassParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updatePass,
		arg.ID,
		arg.ApartmentID,
		arg.CarPlate,
		arg.GuestName,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Status,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
