// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveTodayByApartmentID(ctx context.Context, arg CountActiveTodayByApartmentIDParams) (int64, error)
	CountActiveTodayByResidentID(ctx context.Context, arg CountActiveTodayByResidentIDParams) (int64, error)
	CountValidScansToday(ctx context.Context, scannedAt time.Time) (int64, error)
	CreatePass(ctx context.Context, arg CreatePassParams) (CreatePassRow, error)
	CreateResident(ctx context.Context, arg CreateResidentParams) (CreateResidentRow, error)
	CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error)
	CreateScanEvent(ctx context.Context, arg CreateScanEventParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteResident(ctx context.Context, id int64) error
	GetActivePassByCarPlate(ctx context.Context, arg GetActivePassByCarPlateParams) (GetActivePassByCarPlateRow, error)
	GetActivePassesByApartmentID(ctx context.Context, arg GetActivePassesByApartmentIDParams) ([]GetActivePassesByApartmentIDRow, error)
	GetActivePassesByBuildingID(ctx context.Context, arg GetActivePassesByBuildingIDParams) ([]GetActivePassesByBuildingIDRow, error)
	GetActivePassesByResidentID(ctx context.Context, arg GetActivePassesByResidentIDParams) ([]GetActivePassesByResidentIDRow, error)
	GetApartmentByID(ctx context.Context, id int64) (Apartment, error)
	GetApartmentByResidentTelegramID(ctx context.Context, telegramID int64) (Apartment, error)
	GetApartmentsByBuildingID(ctx context.Context, buildingID int64) ([]Apartment, error)
	GetBuildingByID(ctx context.Context, id int64) (Building, error)
	GetPassByID(ctx context.Context, id uuid.UUID) (GetPassByIDRow, error)
	GetPassesByApartmentIDAndStatus(ctx context.Context, arg GetPassesByApartmentIDAndStatusParams) ([]GetPassesByApartmentIDAndStatusRow, error)
	GetResidentByID(ctx context.Context, id int64) (Resident, error)
	GetResidentByTelegramID(ctx context.Context, telegramID int64) (Resident, error)
	GetRuleByBuildingID(ctx context.Context, buildingID int64) (Rule, error)
	GetScanEventStatistics(ctx context.Context, arg GetScanEventStatisticsParams) (GetScanEventStatisticsRow, error)
	GetScanEventsWithDetails(ctx context.Context, arg GetScanEventsWithDetailsParams) ([]GetScanEventsWithDetailsRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	ListBuildings(ctx context.Context) ([]Building, error)
	ListResidents(ctx context.Context, arg ListResidentsParams) ([]Resident, error)
	ListScanEvents(ctx context.Context, arg ListScanEventsParams) ([]ScanEvent, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RevokePass(ctx context.Context, id uuid.UUID) error
	SearchPassesByCarPlate(ctx context.Context, arg SearchPassesByCarPlateParams) ([]SearchPassesByCarPlateRow, error)
	UpdatePass(ctx context.Context, arg UpdatePassParams) (time.Time, error)
	UpdateResident(ctx context.Context, arg UpdateResidentParams) (time.Time, error)
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (time.Time, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (time.Time, error)
	UpsertResident(ctx context.Context, arg UpsertResidentParams) (UpsertResidentRow, error)
}

var _ Querier = (*Queries)(nil)
