// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: residents.sql

package db

import (
	"context"
	"time"
)

const createResident = `-- name: CreateResident :one
INSERT INTO residents (apartment_id, telegram_id, chat_id, name, phone, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type CreateResidentParams struct {
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	Status      string
}

type CreateResidentRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (CreateResidentRow, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.Status,
	)
	var i CreateResidentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteResident = `-- name: DeleteResident :exec
DELETE FROM residents WHERE id = $1
`

func (q *Queries) DeleteResident(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResident, id)
	return err
}

const getResidentByID = `-- name: GetResidentByID :one
SELECT id, apartment_id, telegram_id, chat_id, name, phone, status, created_at, updated_at
FROM residents
WHERE id = $1
`

func (q *Queries) GetResidentByID(ctx context.Context, id int64) (Resident, error) {
	row := q.db.QueryRow(ctx, getResidentByID, id)
	var i Resident
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.TelegramID,
		&i.ChatID,
		&i.Name,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResidentByTelegramID = `-- name: GetResidentByTelegramID :one
SELECT id, apartment_id, telegram_id, chat_id, name, phone, status, created_at, updated_at
FROM residents
WHERE telegram_id = $1
`

func (q *Queries) GetResidentByTelegramID(ctx context.Context, telegramID int64) (Resident, error) {
	row := q.db.QueryRow(ctx, getResidentByTelegramID, telegramID)
	var i Resident
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.TelegramID,
		&i.ChatID,
		&i.Name,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResidents = `-- name: ListResidents :many
SELECT id, apartment_id, telegram_id, chat_id, name, phone, status, created_at, updated_at
FROM residents
WHERE ($1::bigint IS NULL OR apartment_id = $1)
  AND ($2::bigint IS NULL OR apartment_id IN (SELECT id FROM apartments WHERE building_id = $2))
  AND ($3::varchar IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListResidentsParams struct {
	FilterApartmentID *int64
	FilterBuildingID  *int64
	FilterStatus      *string
	ResultsOffset     *int32
	MaxResults        *int32
}

func (q *Queries) ListResidents(ctx context.Context, arg ListResidentsParams) ([]Resident, error) {
	rows, err := q.db.Query(ctx, listResidents,
		arg.FilterApartmentID,
		arg.FilterBuildingID,
		arg.FilterStatus,
		arg.ResultsOffset,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resident
	for rows.Next() {
		var i Resident
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.TelegramID,
			&i.ChatID,
			&i.Name,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResident = `-- name: UpdateResident :one
UPDATE residents
SET apartment_id = $2, telegram_id = $3, chat_id = $4, name = $5, phone = $6, status = $7
WHERE id = $1
RETURNING updated_at
`

type UpdateResidentParams struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	Status      string
}

func (q *Queries) UpdateResident(ctx context.Context, arg UpdateResidentParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateResident,
		arg.ID,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.Status,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const upsertResident = `-- name: UpsertResident :one
INSERT INTO residents (apartment_id, telegram_id, chat_id, name, phone, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (telegram_id) DO UPDATE SET
    apartment_id = EXCLUDED.apartment_id,
    chat_id = EXCLUDED.chat_id,
    name = EXCLUDED.name,
    phone = EXCLUDED.phone,
    status = EXCLUDED.status
RETURNING id, created_at, updated_at
`

type UpsertResidentParams struct {
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	Status      string
}

type UpsertResidentRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertResident(ctx context.Context, arg UpsertResidentParams) (UpsertResidentRow, error) {
	row := q.db.QueryRow(ctx, upsertResident,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.Status,
	)
	var i UpsertResidentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
