// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: residents.sql

package db

import (
	"context"
	"time"
)

const createResident = `-- name: CreateResident :one
INSERT INTO residents (apartment_id, telegram_id, chat_id, name, phone, car_plate, timezone, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at
`

type CreateResidentParams struct {
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
}

type CreateResidentRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) (CreateResidentRow, error) {
	row := q.db.QueryRow(ctx, createResident,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.CarPlate,
		arg.Timezone,
		arg.Status,
	)
	var i CreateResidentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteResident = `-- name: DeleteResident :exec
DELETE FROM residents WHERE id = $1
`

func (q *Queries) DeleteResident(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResident, id)
	return err
}

const getResidentByID = `-- name: GetResidentByID :one
SELECT id, apartment_id, telegram_id, chat_id, name, phone, car_plate, timezone, status, created_at, updated_at
FROM residents
WHERE id = $1
`

type GetResidentByIDRow struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetResidentByID(ctx context.Context, id int64) (GetResidentByIDRow, error) {
	row := q.db.QueryRow(ctx, getResidentByID, id)
	var i GetResidentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.TelegramID,
		&i.ChatID,
		&i.Name,
		&i.Phone,
		&i.CarPlate,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResidentByTelegramID = `-- name: GetResidentByTelegramID :one
SELECT id, apartment_id, telegram_id, chat_id, name, phone, car_plate, timezone, status, created_at, updated_at
FROM residents
WHERE telegram_id = $1
`

type GetResidentByTelegramIDRow struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetResidentByTelegramID(ctx context.Context, telegramID int64) (GetResidentByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getResidentByTelegramID, telegramID)
	var i GetResidentByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.TelegramID,
		&i.ChatID,
		&i.Name,
		&i.Phone,
		&i.CarPlate,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveResidentsWithCarPlate = `-- name: ListActiveResidentsWithCarPlate :many
SELECT r.id, r.apartment_id, r.telegram_id, r.chat_id, r.name, r.phone, r.car_plate, r.timezone, r.status, r.created_at, r.updated_at
FROM residents r
INNER JOIN apartments a ON r.apartment_id = a.id
WHERE r.status = 'active'
  AND r.car_plate IS NOT NULL
  AND BTRIM(r.car_plate::text) <> ''
  AND ($1::bigint IS NULL OR a.building_id = $1)
ORDER BY r.id
`

type ListActiveResidentsWithCarPlateRow struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListActiveResidentsWithCarPlate(ctx context.Context, filterBuildingID *int64) ([]ListActiveResidentsWithCarPlateRow, error) {
	rows, err := q.db.Query(ctx, listActiveResidentsWithCarPlate, filterBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveResidentsWithCarPlateRow
	for rows.Next() {
		var i ListActiveResidentsWithCarPlateRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.TelegramID,
			&i.ChatID,
			&i.Name,
			&i.Phone,
			&i.CarPlate,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResidentTelegramIDsIn = `-- name: ListResidentTelegramIDsIn :many
SELECT telegram_id
FROM residents
WHERE telegram_id = ANY($1::bigint[])
`

func (q *Queries) ListResidentTelegramIDsIn(ctx context.Context, dollar_1 []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listResidentTelegramIDsIn, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var telegram_id int64
		if err := rows.Scan(&telegram_id); err != nil {
			return nil, err
		}
		items = append(items, telegram_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResidents = `-- name: ListResidents :many
SELECT id, apartment_id, telegram_id, chat_id, name, phone, car_plate, timezone, status, created_at, updated_at
FROM residents
WHERE ($1::bigint IS NULL OR apartment_id = $1)
  AND ($2::bigint IS NULL OR apartment_id IN (SELECT id FROM apartments WHERE building_id = $2))
  AND ($3::varchar IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListResidentsParams struct {
	FilterApartmentID *int64
	FilterBuildingID  *int64
	FilterStatus      *string
	ResultsOffset     *int32
	MaxResults        *int32
}

type ListResidentsRow struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListResidents(ctx context.Context, arg ListResidentsParams) ([]ListResidentsRow, error) {
	rows, err := q.db.Query(ctx, listResidents,
		arg.FilterApartmentID,
		arg.FilterBuildingID,
		arg.FilterStatus,
		arg.ResultsOffset,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResidentsRow
	for rows.Next() {
		var i ListResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.TelegramID,
			&i.ChatID,
			&i.Name,
			&i.Phone,
			&i.CarPlate,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResidentCarPlate = `-- name: SetResidentCarPlate :exec
UPDATE residents
SET car_plate = $2
WHERE id = $1
`

type SetResidentCarPlateParams struct {
	ID       int64
	CarPlate *string
}

func (q *Queries) SetResidentCarPlate(ctx context.Context, arg SetResidentCarPlateParams) error {
	_, err := q.db.Exec(ctx, setResidentCarPlate, arg.ID, arg.CarPlate)
	return err
}

const setResidentTimezone = `-- name: SetResidentTimezone :exec
UPDATE residents
SET timezone = $2
WHERE id = $1
`

type SetResidentTimezoneParams struct {
	ID       int64
	Timezone *string
}

func (q *Queries) SetResidentTimezone(ctx context.Context, arg SetResidentTimezoneParams) error {
	_, err := q.db.Exec(ctx, setResidentTimezone, arg.ID, arg.Timezone)
	return err
}

const updateResident = `-- name: UpdateResident :one
UPDATE residents
SET apartment_id = $2, telegram_id = $3, chat_id = $4, name = $5, phone = $6, car_plate = $7, timezone = $8, status = $9
WHERE id = $1
RETURNING updated_at
`

type UpdateResidentParams struct {
	ID          int64
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Timezone    *string
	Status      string
}

func (q *Queries) UpdateResident(ctx context.Context, arg UpdateResidentParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateResident,
		arg.ID,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.CarPlate,
		arg.Timezone,
		arg.Status,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const upsertResident = `-- name: UpsertResident :one
INSERT INTO residents (apartment_id, telegram_id, chat_id, name, phone, car_plate, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (telegram_id) DO UPDATE SET
    apartment_id = EXCLUDED.apartment_id,
    chat_id = EXCLUDED.chat_id,
    name = EXCLUDED.name,
    phone = EXCLUDED.phone,
    car_plate = EXCLUDED.car_plate,
    status = EXCLUDED.status
RETURNING id, created_at, updated_at
`

type UpsertResidentParams struct {
	ApartmentID int64
	TelegramID  int64
	ChatID      int64
	Name        *string
	Phone       *string
	CarPlate    *string
	Status      string
}

type UpsertResidentRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertResident(ctx context.Context, arg UpsertResidentParams) (UpsertResidentRow, error) {
	row := q.db.QueryRow(ctx, upsertResident,
		arg.ApartmentID,
		arg.TelegramID,
		arg.ChatID,
		arg.Name,
		arg.Phone,
		arg.CarPlate,
		arg.Status,
	)
	var i UpsertResidentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
