// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rules.sql

package db

import (
	"context"
	"time"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (building_id, quiet_hours_start, quiet_hours_end,
                   daily_pass_limit_per_apartment, max_pass_duration_hours)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at
`

type CreateRuleParams struct {
	BuildingID                 int64
	QuietHoursStart            *string
	QuietHoursEnd              *string
	DailyPassLimitPerApartment int32
	MaxPassDurationHours       int32
}

type CreateRuleRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.BuildingID,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.DailyPassLimitPerApartment,
		arg.MaxPassDurationHours,
	)
	var i CreateRuleRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getRuleByBuildingID = `-- name: GetRuleByBuildingID :one
SELECT id, building_id, quiet_hours_start, quiet_hours_end,
       daily_pass_limit_per_apartment, max_pass_duration_hours, created_at, updated_at
FROM rules
WHERE building_id = $1
`

func (q *Queries) GetRuleByBuildingID(ctx context.Context, buildingID int64) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleByBuildingID, buildingID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.DailyPassLimitPerApartment,
		&i.MaxPassDurationHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET quiet_hours_start = $2, quiet_hours_end = $3,
    daily_pass_limit_per_apartment = $4, max_pass_duration_hours = $5
WHERE id = $1
RETURNING updated_at
`

type UpdateRuleParams struct {
	ID                         int64
	QuietHoursStart            *string
	QuietHoursEnd              *string
	DailyPassLimitPerApartment int32
	MaxPassDurationHours       int32
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.DailyPassLimitPerApartment,
		arg.MaxPassDurationHours,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
