// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countValidScansToday = `-- name: CountValidScansToday :one
SELECT COUNT(*)
FROM scan_events
WHERE result = 'valid' AND scanned_at >= $1
`

func (q *Queries) CountValidScansToday(ctx context.Context, scannedAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countValidScansToday, scannedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanEvent = `-- name: CreateScanEvent :one
INSERT INTO scan_events (pass_id, guard_user_id, scanned_at, result, reason, meta)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
RETURNING id
`

type CreateScanEventParams struct {
	PassID      uuid.UUID
	GuardUserID int64
	ScannedAt   time.Time
	Result      string
	Reason      *string
	Meta        []byte
}

func (q *Queries) CreateScanEvent(ctx context.Context, arg CreateScanEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createScanEvent,
		arg.PassID,
		arg.GuardUserID,
		arg.ScannedAt,
		arg.Result,
		arg.Reason,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getScanEventStatistics = `-- name: GetScanEventStatistics :one
SELECT
    COUNT(*) as total_scans,
    COUNT(*) FILTER (WHERE se.result = 'valid') as valid_scans,
    COUNT(*) FILTER (WHERE se.result = 'invalid') as invalid_scans,
    COUNT(DISTINCT se.pass_id) as unique_passes,
    COUNT(DISTINCT se.guard_user_id) as unique_guards
FROM scan_events se
INNER JOIN passes p ON se.pass_id = p.id
INNER JOIN apartments a ON p.apartment_id = a.id
WHERE ($1::timestamp IS NULL OR se.scanned_at >= $1)
  AND ($2::timestamp IS NULL OR se.scanned_at <= $2)
  AND ($3::bigint IS NULL OR a.building_id = $3)
`

type GetScanEventStatisticsParams struct {
	FilterFrom       pgtype.Timestamp
	FilterTo         pgtype.Timestamp
	FilterBuildingID *int64
}

type GetScanEventStatisticsRow struct {
	TotalScans   int64
	ValidScans   int64
	InvalidScans int64
	UniquePasses int64
	UniqueGuards int64
}

func (q *Queries) GetScanEventStatistics(ctx context.Context, arg GetScanEventStatisticsParams) (GetScanEventStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getScanEventStatistics, arg.FilterFrom, arg.FilterTo, arg.FilterBuildingID)
	var i GetScanEventStatisticsRow
	err := row.Scan(
		&i.TotalScans,
		&i.ValidScans,
		&i.InvalidScans,
		&i.UniquePasses,
		&i.UniqueGuards,
	)
	return i, err
}

const getScanEventsWithDetails = `-- name: GetScanEventsWithDetails :many
SELECT
    se.id, se.pass_id, se.guard_user_id, se.scanned_at, se.result, se.reason, se.meta,
    p.car_plate, a.number as apartment_number, a.building_id,
    u.username as guard_username
FROM scan_events se
INNER JOIN passes p ON se.pass_id = p.id
INNER JOIN apartments a ON p.apartment_id = a.id
LEFT JOIN users u ON se.guard_user_id = u.id
WHERE ($1::bigint IS NULL OR a.building_id = $1)
  AND ($2::uuid IS NULL OR se.pass_id = $2)
  AND ($3::bigint IS NULL OR se.guard_user_id = $3)
  AND ($4::varchar IS NULL OR se.result = $4)
  AND ($5::varchar IS NULL OR a.number ILIKE '%' || $5 || '%')
  AND ($6::varchar IS NULL OR p.car_plate ILIKE '%' || $6 || '%')
  AND ($7::timestamp IS NULL OR se.scanned_at >= $7)
  AND ($8::timestamp IS NULL OR se.scanned_at <= $8)
ORDER BY se.scanned_at DESC
LIMIT $10
OFFSET $9
`

type GetScanEventsWithDetailsParams struct {
	FilterBuildingID      *int64
	FilterPassID          pgtype.UUID
	FilterGuardUserID     *int64
	FilterResult          *string
	FilterApartmentNumber *string
	FilterCarPlate        *string
	FilterFrom            pgtype.Timestamp
	FilterTo              pgtype.Timestamp
	ResultsOffset         *int32
	MaxResults            *int32
}

type GetScanEventsWithDetailsRow struct {
	ID              int64
	PassID          uuid.UUID
	GuardUserID     int64
	ScannedAt       time.Time
	Result          string
	Reason          *string
	Meta            []byte
	CarPlate        *string
	ApartmentNumber string
	BuildingID      int64
	GuardUsername   *string
}

func (q *Queries) GetScanEventsWithDetails(ctx context.Context, arg GetScanEventsWithDetailsParams) ([]GetScanEventsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getScanEventsWithDetails,
		arg.FilterBuildingID,
		arg.FilterPassID,
		arg.FilterGuardUserID,
		arg.FilterResult,
		arg.FilterApartmentNumber,
		arg.FilterCarPlate,
		arg.FilterFrom,
		arg.FilterTo,
		arg.ResultsOffset,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScanEventsWithDetailsRow
	for rows.Next() {
		var i GetScanEventsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.PassID,
			&i.GuardUserID,
			&i.ScannedAt,
			&i.Result,
			&i.Reason,
			&i.Meta,
			&i.CarPlate,
			&i.ApartmentNumber,
			&i.BuildingID,
			&i.GuardUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanEvents = `-- name: ListScanEvents :many
SELECT id, pass_id, guard_user_id, scanned_at, result, reason, meta
FROM scan_events
WHERE ($1::uuid IS NULL OR pass_id = $1)
  AND ($2::bigint IS NULL OR guard_user_id = $2)
  AND ($3::varchar IS NULL OR result = $3)
  AND ($4::timestamp IS NULL OR scanned_at >= $4)
  AND ($5::timestamp IS NULL OR scanned_at <= $5)
ORDER BY scanned_at DESC
LIMIT $7
OFFSET $6
`

type ListScanEventsParams struct {
	FilterPassID      pgtype.UUID
	FilterGuardUserID *int64
	FilterResult      *string
	FilterFrom        pgtype.Timestamp
	FilterTo          pgtype.Timestamp
	ResultsOffset     *int32
	MaxResults        *int32
}

func (q *Queries) ListScanEvents(ctx context.Context, arg ListScanEventsParams) ([]ScanEvent, error) {
	rows, err := q.db.Query(ctx, listScanEvents,
		arg.FilterPassID,
		arg.FilterGuardUserID,
		arg.FilterResult,
		arg.FilterFrom,
		arg.FilterTo,
		arg.ResultsOffset,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanEvent
	for rows.Next() {
		var i ScanEvent
		if err := rows.Scan(
			&i.ID,
			&i.PassID,
			&i.GuardUserID,
			&i.ScannedAt,
			&i.Result,
			&i.Reason,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
