// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role, building_id, apartment_number, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at
`

type CreateUserParams struct {
	Username        string
	Email           *string
	PasswordHash    string
	Role            string
	BuildingID      *int64
	ApartmentNumber *int32
	Status          string
}

type CreateUserRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.BuildingID,
		arg.ApartmentNumber,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, building_id, apartment_number, status, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              int64
	Username        string
	Email           *string
	PasswordHash    string
	Role            string
	BuildingID      *int64
	ApartmentNumber *int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.BuildingID,
		&i.ApartmentNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, building_id, apartment_number, status, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID              int64
	Username        string
	Email           *string
	PasswordHash    string
	Role            string
	BuildingID      *int64
	ApartmentNumber *int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.BuildingID,
		&i.ApartmentNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, building_id, apartment_number, status, created_at, updated_at
FROM users
WHERE ($1::varchar IS NULL OR role = $1)
  AND ($2::bigint IS NULL OR building_id = $2)
  AND ($3::varchar IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListUsersParams struct {
	FilterRole       *string
	FilterBuildingID *int64
	FilterStatus     *string
	ResultsOffset    *int32
	MaxResults       *int32
}

type ListUsersRow struct {
	ID              int64
	Username        string
	Email           *string
	PasswordHash    string
	Role            string
	BuildingID      *int64
	ApartmentNumber *int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.FilterRole,
		arg.FilterBuildingID,
		arg.FilterStatus,
		arg.ResultsOffset,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.BuildingID,
			&i.ApartmentNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, email = $3, password_hash = $4, role = $5, building_id = $6, apartment_number = $7, status = $8
WHERE id = $1
RETURNING updated_at
`

type UpdateUserParams struct {
	ID              int64
	Username        string
	Email           *string
	PasswordHash    string
	Role            string
	BuildingID      *int64
	ApartmentNumber *int32
	Status          string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.BuildingID,
		arg.ApartmentNumber,
		arg.Status,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
