apiVersion: v1
kind: Secret
metadata:
  name: yardpass-backend
type: Opaque
stringData:
  database-url: "postgres://yardpass:password@postgres-postgresql:5432/yardpass?sslmode=disable"
  redis-url: "redis://redis-master:6379/0"
