apiVersion: v1
kind: Secret
metadata:
  name: yardpass-backend
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  smtp-host: {{ .Values.secrets.smtpHost | quote }}
  smtp-port: {{ .Values.secrets.smtpPort | quote }}
  smtp-username: {{ .Values.secrets.smtpUsername | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | quote }}
  smtp-from: {{ .Values.secrets.smtpFrom | quote }}
