prometheus:
  prometheusSpec:
    retention: 30d
    retentionSize: "5GB"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
    evaluationInterval: 15s
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

grafana:
  enabled: true
  adminPassword: admin
  persistence:
    enabled: true
    size: 5Gi

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false
